name: Validate bicep scripts
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
env:
 AZURE_LOAD_TEST_NAME: loadtest-uxfkfalgrdeag
 AZURE_RESOURCE_GROUP_NAME: django-test-3-rg
 AZURE_LOAD_TEST_HOST: app-uxfkfalgrdeag.azurewebsites.net
jobs:
  build:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: az bicep build -f infra/main.bicep
      - name: Azure authentication (load testing)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_LT_CREDENTIALS }}
      - name: 'Azure Load Testing'
        uses: tonybaloney/load-testing@write_metrics_to_pr
        with:
          loadTestConfigFile: 'loadtest/smoketest.yaml'
          loadTestResource: ${{ env.AZURE_LOAD_TEST_NAME }}
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          env: |
            [
              {
              "name": "domain",
              "value": "${{ env.AZURE_LOAD_TEST_HOST }}"
              }
            ]
